___
# **NumPy is a Python library** used for working with arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices. It supports large multi-dimensinal arrays and matrices.

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**
NOTE: If you are using COLABS you do not have to install numpy. It will be already installed.

Exercises

For this exercises, we assume that you have NumPy installed in your system.
https://numpy.org/
___

# NumPy Exercises 

We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.



```
# This is formatted as code
```

#### Import NumPy as np

In [53]:
import numpy as np

#### Create an array of 10 zeros 

In [54]:
zeroArray = np.zeros(10)
print("Array:", zeroArray)

Array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [55]:
oneArray = np.ones(10)
print("Array:", oneArray)

Array: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [56]:
fiveArray = np.ones(10) * 5
print("Array:", fiveArray)

Array: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [57]:
tenToFifty = np.arange(10, 51)
print("Integers from 10 to 50:", tenToFifty)

Integers from 10 to 50: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [58]:
evenIntegers = np.arange(10, 51, 2) # We are using the Numpy built-in arrange func(), it takes 3 params: Stop, Start and Step. Since we are looking for 10 to 50 we use 10,51,2.
print(evenIntegers) 

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [59]:
threeByThree = np.arange(9).reshape(3, 3)
print(threeByThree)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [60]:
identityMatrix = np.eye(3)
print(identityMatrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [61]:
randNum = np.random.rand()
print("Random number:", randNum)

Random number: 0.9371370613735187


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [62]:
randNum = np.random.randn(25)
print("Array:")
print(randNum)

Array:
[ 0.61782617 -0.32240805  0.3635288  -0.325866    0.22972479  0.19154602
 -0.82184181  0.06383991 -1.14151851  1.05134955  0.53675495  0.47927959
 -0.82736719  0.97486524 -0.18881974 -0.20469574 -0.41024261 -0.0561444
 -1.23377147  0.46942591  0.32982446  0.11426678 -0.07906567 -1.09052956
 -0.25439889]


#### Create the following matrix:

In [63]:
start = 0.01 # 0.1 increments
stop = 1.0 # set our stop
step = 0.01 # initalise our step

pointMatrix = np.arange(start, stop + step, step).reshape(10, 10)
print(pointMatrix)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [64]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [65]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
resultOne = mat[2:, 1:]
print(resultOne)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [67]:
findTwenty = mat[3, 4]
print(findTwenty)

20


In [68]:
newMatrix = mat[[0,1,2],[1,1,1]]
newMatrix = newMatrix[:, np.newaxis]
print(newMatrix)

[[ 2]
 [ 7]
 [12]]


In [69]:
flatMatrix = mat[4, :,]
print(flatMatrix)

[21 22 23 24 25]


In [70]:
twoByTwo = mat[3:,:]
print(twoByTwo)

[[16 17 18 19 20]
 [21 22 23 24 25]]


### Now do the following

#### Get the sum of all the values in mat

In [71]:
sumValues = np.sum(mat)
print('Sum:', sumValues)

Sum: 325


#### Get the standard deviation of the values in mat

In [72]:
STD = np.std(mat) # built in std measurement
print('Standard Deviation:', STD)

Standard Deviation: 7.211102550927978


#### Get the sum of all the columns in mat

In [73]:
sumColunmz = np.sum(mat, axis=0)
print('Array:', sumColunmz)


Array: [55 60 65 70 75]
